### ISSUE TITLE
 ⚠️ "Remove imports => remove Lua 'requires'" breaks bundle because imports never called

### ISSUE THREAD

**Issue by websharik** [mtasa-typescript/mtasa-lua-utils#24]
I try make bundle with low level TSTL API:
```javascript
const tstl = require("typescript-to-lua")
function makeBundleFile(filePath, conf) {
  return new Promise(async (resolve, reject) => {
    try {
      let result = await tstl.transpileFiles([filePath], {
        //original from tsconfig.json (wtf mix ts and tstl)
        compilerOptions: {
          ...conf.compilerOptions
        },
        tstl: {
          ...conf.tstl
        },
        plugins: [
          ...conf.compilerOptions.plugins
        ],
        types: ["lua-types/5.1"],
        ...conf.tstl,
        //if not . then put out to src
        rootDir: ".",
        //out path with same name from src
        luaBundle: `${conf.compilerOptions.outDir}/${path.basename(filePath).replace('.ts', '.lua')}`,
        //entry point
        luaBundleEntry: filePath
      })
      console.log(result)
      resolve(result)
    } catch (e) {
      reject(e)
    }
  })
}
```
test_ts.ts
```typescript
import { msg } from "./separatedFile"
print(`msg: ${msg}`)
```

separatedFile.ts
```typescript
export const msg = 'Hello world'
```
result:
```lua
local ____modules = {}
local ____moduleCache = {}
local ____originalRequire = require
local function require(file)
    if ____moduleCache[file] then
        return ____moduleCache[file]
    end
    if ____modules[file] then
        ____moduleCache[file] = ____modules[file]()
        return ____moduleCache[file]
    else
        if ____originalRequire then
            return ____originalRequire(file)
        else
            error("module '" .. file .. "' not found")
        end
    end
end
____modules = {
["src.example.separatedFile"] = function()
local ____exports = {}
____exports.msg = "Hello world"
_G.msg = ____exports.msg
return ____exports
 end,
["src.example.test_ts"] = function()
local ____exports = {}
print("msg: " .. msg)
return ____exports
 end,
}
return require("src.example.test_ts")
```
`src.example.separatedFile` never called and `msg` is stay `undefined`

Mb add plugins option to disable remove imports ? Or else solution...

**Comment by websharik** [comment]
Fix for me. But its start new problem... noside files can contain server/client imports - deep check required.
```javascript
// Remove imports => remove lua 'requires'
if (anti_import_1.isImportNode(node)) {
    if (props.side != undefined) return undefined;
}
```

**Comment by Toliak** [comment]
1. What structure of the bundle file do you expect? 
    a. A single file for client- and server-side, like
```lua
IS_CLIENT = _G.addBan == nil
if (IS_CLIENT) then
    ...
else
    ,,,
end
```
    b. Separated files for client- and server-side
    c. Something else :)
2. Have you tried to bypass (or remove) mtasa-lua-utils plugin (to restore import behaviour)? I have and I stucked in [this](https://github.com/TypeScriptToLua/TypeScriptToLua/issues/1070).

**Comment by websharik** [comment]
@Toliak, 1. b :)

**Comment by websharik** [comment]
@Toliak, 2. Yes I try and it's working. I'm add check to until - if side not detected then don't remove require.


> Fix for me. But its start new problem... noside files can be contain server/client imports - deep check required.
> 
> ```js
> // Remove imports => remove lua 'requires'
> if (anti_import_1.isImportNode(node)) {
>     if (props.side != undefined) return undefined;
> }
> ```

**Comment by Toliak** [comment]
[The issue about creating multiple resources in the same boilerplate](https://github.com/mtasa-typescript/resource-boilerplate/issues/27) should be mentioned here.
So, for multiple resources the utils should generate bundled `client.lua` and `server.lua` for each resource.

---

What can I suggest (and, I believe, implement :D) as a solution:
1. Custom meta file: `meta.yml` [(because we store data in meta, not a markup)](https://stackoverflow.com/questions/1308536/yaml-compared-to-xml#:~:text=The%20biggest%20difference%2C%20though%2C%20is,text%20is%20awkward%20to%20represent.)
It will look like:
```yaml
info:
  name: My Resource 1
  type: script
oop: true

scripts:
  - src: something.lua
    type: server

---

info:
  name: My Resource 2
  type: script
oop: true

scripts:
  - src: another.lua
    type: client

bundledScripts:
  - tsSrc: entrypoint.ts
    src: entrypoint.lua
    type: server

```

2. Write compiler wrapper (like you did [here](https://github.com/mtasa-typescript/mtasa-lua-utils/issues/24#issue-962798698))

3. Produce `meta.xml` files, based on `meta.yml` for each resources

Example for the `meta.yml` above:
```xml
<meta>
    <info name="My Resource 1" type="script" />
    <oop>true</oop>

    <script src="something.lua" type="server" />
</meta>
```

```xml
<meta>
    <info name="My Resource 2" type="script" />
    <oop>true</oop>

    <script src="another.lua" type="client" />

    <script src="entrypoint.lua" type="server" />
</meta>
```

In the result we will receive:
- ability to make bundle files (and mix them with not-bundled scripts)
- ability to correctly determine the script side
- ability to create multiple resources from one boilerplate

**Comment by websharik** [comment]
@Toliak Its good. But problem is another or im not understand suggest solution... just look code.
Original (left) works, after utils (right) not works. 

![2021-08-07_17-52-16](https://user-images.githubusercontent.com/33082364/128604385-038d65bf-df94-4310-813a-d56d7da437a2.jpg)

Its becouse modules is table with functions, and when "require" called function from start table work.
Utils cut all requires inside modules. Module `src.example.separatedFile` never called and 
`_G.msg = ____exports.msg` never working. So `msg` in `src.example.test_ts` is `undefined`

My resolve: if required module not from `mtasa` then allow import them (my upper comment). But add recursive check inside this module to check his requires to can warning "Not mix server/client side".

**Comment by websharik** [comment]
Can your release it, pls ?

**Comment by Toliak** [comment]
@websharik Yes, I'm going to release it as v0.2.3

v0.2 is still unstable, because I haven't tested all features yet, so, if you'll find any bugs -- feel free to comment here, or create a new issue

**Comment by websharik** [comment]
Here We Go Again...
![2023-05-05_13-57-27](https://user-images.githubusercontent.com/33082364/236440720-c462a7ad-cb41-4423-b0a1-4c7fb25e7cfa.png)

Module `SandBox.server` dont know `Test` because it import was removed. I was clone your repo and try upgrade to latest TSTL + some paths. All done without that bug. server.ts - main bundeled entry point for server. Test.ts - some external-file self resource class.

How i can disable 'removing require from self resource in bundle mode' now ?

UPD: Solved... add to `prepareGlobalImports` (in `prepareImports.ts`)
```ts
if (isLocalImport(node, context)) {
  return context.superTransformStatements(node);
}
```
